portfolios:
  - name: examples
    description: |
      Portfolio for example products.
    provider_name: tech_org
    usage_policy_arns:
      - arn:aws:iam::aws:policy/AmazonS3FullAccess
    groups:
      - Administrators
      - Developers
    products:
      - name: example-bucket
        owner: platform
        type: CLOUD_FORMATION_TEMPLATE
        version: "0"
