portfolios:
  - name: examples
    description: |
      Portfolio for example products.
    provider_name: tech_org
    groups:
      - Administrators
      - Developers
    products:
      - name: example-bucket
        owner: platform
        type: CLOUD_FORMATION_TEMPLATE
        version: "0.1"
        launch_constraint:arn:aws:iam::aws:policy/AmazonS3FullAccess
