repos:
  # Existing Terraform hooks
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.96.2
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint
      # - id: terraform_docs [TODO: enable this hook]

  # Existing generic hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      # - id: check-yaml [TODO: enable this hook]
      - id: check-json

  # Detect secrets
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets

  # Enforce Conventional Commits
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.6.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [--strict, --force-scope, feat, fix, chore, test, custom]

  # CloudFormation Linter (cfn-lint)
  - repo: https://github.com/aws-cloudformation/cfn-lint
    rev: v1.20.0  # Replace with the latest version as needed
    hooks:
      - id: cfn-lint
        files: ^(templates/|portfolios/).*\.(yaml|yml)$
