portfolios:
  - name: examples
    description: |
      Portfolio for example products.
    provider_name: tech_org
    products:
      - name: example-bucket
        owner: platform
        type: CLOUD_FORMATION_TEMPLATE
        version: 0
