---
template-file-path: bootstrap/002-management-pipeline.yaml
parameters:
  ArtifactStorageBucketName: "artifact-storage"
  BuildSpecStorageBucketName: "buildspec-storage"
  StateBucketName: "terraform-state"
  StateLockTableName: "state-lock-table"
  LowerCaseStackName: "svccatman"
tags:
  Service: "Service Catalog Manager"
