---
template-file-path: bootstrap/svc-cat-man-bootstrap.yml
parameters:
  EnableJSM: false
  ArtifactStorageBucketName: artifact-storage
  BuildSpecStorageBucketName: buildspec-storage
  StateBucketName: terraform-state
  StateLockTableName: state-lock-table
  # yamllint disable-line rule:line-length
  GitHubSecretARN: arn:aws:secretsmanager:eu-west-2:575108940418:secret:github_token-MquYHN
  # yamllint disable-line rule:line-length
  CodeConnectionARN: arn:aws:codeconnections:eu-west-2:575108940418:connection/7b810aeb-23af-4a88-9a51-b39d72cc1064
tags: {}
