---
template-file-path: bootstrap/svc-cat-man-bootstrap.yml
parameters:
  EnableJSM: false
  ArtifactStorageBucketName: artifact-storage
  BuildSpecStorageBucketName: buildspec-storage
  StateBucketName: terraform-state
  StateLockTableName: state-lock-table
tags: {}
