version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies..."
      - apt-get update && apt-get install -y unzip curl
      - curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
      - echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
      - apt-get update && apt-get install -y terraform

  pre_build:
    commands:
      - echo "Preparing deployment: $ENVIRONMENT"
      - echo "Unzipping source artifact..."
      - mkdir -p /tmp/source
      - unzip -o artifact.zip -d /tmp/source

  build:
    commands:
      - echo "Starting deployment: $ENVIRONMENT"
      - cd /tmp/source
      - echo "Initializing Terraform..."
      - terraform init
      - echo "Validating Terraform..."
      - terraform validate
      - echo "Applying Terraform..."
      - TF_VAR_environment=$ENVIRONMENT terraform apply -auto-approve

  post_build:
    commands:
      - echo "Deployment completed: $ENVIRONMENT"

artifacts:
  files:
    - '**/*'
  discard-paths: no
