---
version: 0.2

env:
  variables:
    TF_IN_AUTOMATION: 1

phases:
  install:
    environment:
      PATH: "/usr/local/go/bin:/go/bin:${PATH}"
      GOPATH: "/go"
    commands:
      - wget https://go.dev/dl/go1.23.4.linux-amd64.tar.gz
      - tar -C /usr/local -xzf go1.23.4.linux-amd64.tar.gz
      - /usr/local/go/bin/go install github.com/dineshba/tf-summarize@latest

  build:
    commands:
      - cd terraform/
      - echo "Initializing Terraform..."
      - terraform init -input=false
      - echo "Validating Terraform..."
      - terraform validate
      - echo "Planning Terraform..."
      - terraform plan -out=tfplan -input=false > /dev/null
      - echo "Summarizing Terraform plan..."
      - terraform show -json tfplan | tf-summarize
      - echo "Applying Terraform..."
      - terraform apply -input=false tfplan

artifacts:
  files:
    - '**/*'
  discard-paths: no
