---
version: 0.2

env:
  variables:
    TF_IN_AUTOMATION: 1

phases:
  install:
    commands:
      - wget https://go.dev/dl/go1.23.4.linux-amd64.tar.gz
      - tar -C /usr/local -xzf go1.23.4.linux-amd64.tar.gz
      - export PATH=$PATH:/usr/local/go/bin
      - export GOPATH=/go
      - /usr/local/go/bin/go install github.com/dineshba/tf-summarize@latest
      - export PATH=$PATH:/go/bin

  build:
    commands:
      - cd terraform/
      - echo "Initializing Terraform..."
      - terraform init -input=false -lock=false > /dev/null
      - echo "Validating Terraform..."
      - terraform validate
      - echo "Planning Terraform..."
      - |
        terraform plan \
          -compact-warnings \
          -out=tfplan \
          -input=false \
          -lock-timeout=30s
      - echo "Summarizing Terraform plan..."
      - terraform show -json tfplan | tf-summarize
      - echo "Applying Terraform..."
      - |
        terraform apply \
          -compact-warnings \
          -input=false \
          -lock-timeout=30s \
          -backup=/tmp/svccatman-terraform-state_$(date +%Y-%m-%d).tar.gz \
          tfplan

artifacts:
  files:
    - /tmp/svccatman-terraform-state_$(date +%Y-%m-%d).tar.gz
    - '**/*'
  discard-paths: no
