---
version: 0.2

phases:
  build:
    commands:
      # Change to the secondary artifact directory
      - cd terraform/
      - echo "Initializing Terraform..."
      - terraform init
      - echo "Validating Terraform..."
      - terraform validate
      - echo "Planning Terraform..."
      - terraform plan
      - echo "Applying Terraform..."
      - terraform apply -auto-approve

artifacts:
  files:
    # yamllint disable-line rule:truthy
    - '**/*'
  discard-paths: no
