---
version: 0.2

env:
  # BuildSpec secrets manager reference:
  # https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html#build-spec.env.secrets-manager
  secrets-manager:
    # yamllint disable-line rule:line-length
    GITHUB_APP_ID: "github_app_config:github_app_id"
    GITHUB_APP_INSTALLATION_ID: "github_app_config:github_app_installation_id"
    GITHUB_APP_PEM_FILE: "github_app_config:github_app_pem_file"

phases:
  build:
    commands:
      # Change to the secondary artifact directory
      - cd $CODEBUILD_SRC_DIR_SourceArtifact
      - echo "Initializing Terraform..."
      - terraform init
      - echo "Validating Terraform..."
      - terraform validate
      - echo "Planning Terraform..."
      - terraform plan
      - echo "Applying Terraform..."
      - terraform apply -auto-approve

artifacts:
  files:
    # yamllint disable-line rule:truthy
    - '**/*'
  discard-paths: no
