version: 0.2


env:
  secrets-manager:
    # yamllint disable-line rule:line-length
    GITHUB_TOKEN: "github_token:GITHUB_TOKEN"
phases:
  build:
    commands:
      # change to secondary artifact directory
      - cd $CODEBUILD_SRC_DIR_SourceArtifact
      - echo "Initializing Terraform..."
      - terraform init
      - echo "Selecting workspace..."
      - terraform workspace select -or-create=true $ENVIRONMENT
      - echo "Validating Terraform..."
      - terraform validate
      - echo "Planning Terraform..."
      - TF_VAR_environment="${ENVIRONMENT}" terraform plan
      - echo "Applying Terraform..."
      - TF_VAR_environment="${ENVIRONMENT}" terraform apply -auto-approve

artifacts:
  files:
    - '**/*'
  discard-paths: no
