version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - apt-get update && apt-get install -y unzip curl gnupg
      - curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
      - echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
      - apt-get update && apt-get install -y terraform

  pre_build:
    commands:
      - echo "Preparing source artifact..."
      - mkdir -p /tmp/source
      - unzip -o artifact.zip -d /tmp/source

  build:
    commands:
      - echo "Initializing Terraform..."
      - cd /tmp/source
      - terraform init
      - echo "Validating Terraform..."
      - terraform validate
      - echo "Applying Terraform..."
      - terraform apply -auto-approve -var="environment=$ENVIRONMENT"

artifacts:
  files:
    - '**/*'
  discard-paths: no
