---
AWSTemplateFormatVersion: "2010-09-09"
Description: Simple CloudFormation template to deploy a DynamoDB table
Resources:
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: ArtistId
          AttributeType: S
        - AttributeName: Concert
          AttributeType: S
      KeySchema:
        - AttributeName: ArtistId
          KeyType: HASH
        - AttributeName: Concert
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: sample-table
