---
name: Publish BuildSpecs

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
    paths:
      - 'buildspecs/**'

jobs:
  publish-buildspecs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Zip and Upload BuildSpecs
        run: |
          mkdir -p buildspecs-zipped
          for dir in buildspecs/*/; do
            foldername=$(basename "$dir")
            zip -j "buildspecs-zipped/${foldername}.zip" "${dir}buildspec.yml"
            echo "Uploading ${foldername}.zip to S3..."
            aws s3 cp "buildspecs-zipped/${foldername}.zip" \
            "s3://${{ secrets.BUILDSPEC_STORAGE_BUCKET }}/${foldername}.zip"
          done
