name: Publish BuildSpecs

on:
  push:
    branches:
      - main

jobs:
  publish-buildspecs:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      # Step 3: Zip and upload buildspec.yml files
      - name: Zip and Upload BuildSpecs
        run: |
          for dir in buildspecs/*/; do
            aws s3 cp  "${dir}buildspec.yml" "s3://${{ secrets.BUILDSPEC_STORAGE_BUCKET }}/${dir}/buildspec.yml"
          done
