name: Publish BuildSpecs

on:
  push:
    branches:
      - main

jobs:
  publish-buildspecs:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      # Step 3: Zip each YAML file in buildspecs/ and upload to S3
      - name: Zip and Upload BuildSpecs
        run: |
          mkdir -p buildspecs
          for file in buildspecs/*.yml; do
            filename=$(basename -- "$file")
            zip -j "${filename%.yml}.zip" "$file"
            echo "Uploading ${filename%.yml}.zip to S3..."
            aws s3 cp "${filename%.yml}.zip" "s3://${{ secrets.BUILDSPEC_STORAGE_BUCKET }}/${filename%.yml}.zip"
          done
